name: VLESS Task Scheduler

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 * * * *'  # Runs every hour, adjust as needed

jobs:
  vless_task:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install paramiko schedule

      - name: Run VLESS Task Script
        env:
          VPS_USERNAME: ${{ secrets.VPS_USERNAME }}
          VPS_PASSWORD: ${{ secrets.VPS_PASSWORD }}
        run: |
          python vless_task.py
